# Generated by Django 3.1.5 on 2021-01-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('type', models.IntegerField(choices=[(1, 'Fundation'), (2, 'Non-goverment organization'), (3, 'Local collection')], default=1)),
                ('categories', models.ManyToManyField(related_name='institutions', to='app_portfolio.Category')),
            ],
        ),
    ]
