# Generated by Django 3.1.5 on 2021-01-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0003_doantion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doantion',
            name='address',
            field=models.CharField(max_length=50),
        ),
    ]
