# Generated by Django 3.1.5 on 2021-01-21 13:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_portfolio', '0004_auto_20210121_1225'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doantion',
            new_name='Donation',
        ),
    ]
