# Generated by Django 3.1.6 on 2021-02-04 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0005_auto_20210121_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='institution',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_portfolio.institution'),
            preserve_default=False,
        ),
    ]
